### PR TITLE
Update Author to use the accountId instead of deprecated name

### PR DESCRIPTION
**Pull request by ricardorlg-aval**
- Jira API deprecate and remove the name field from Author object, now API clients should use accountId, this PR makes a fix for this.
- Update transitions to compare using lowercase  to avoid case strings key comparison errors.

### CODE REVIEW

**Comment by ricardorlg-aval** [comment]
@wakaleo any comments on this, or can this PR be merge.

**Comment by wakaleo** [comment]
Thanks for reminding me @ricardorlg-aval

**Comment by coumarine** [comment]
@wakaleo Please can you confirm the Serenity-Jira Plugin version, which has this fix. Thanks.

**Comment by wakaleo** [comment]
It hasn't been released yet, I will probably do a release later this week or next week.

**Comment by coumarine** [comment]
Thanks much @wakaleo Please can you update here, once done.

**Comment by coumarine** [comment]
@wakaleo Please can you confirm if the fix is release now.
If this would take time, we are ok to role back to older JIRA version. Please advise  JIRA version with which the below serenity-jira-plugin:1.12.0 would work.

**serenity-jira plugin used in our project:**
jira: "net.serenity-bdd:serenity-jira-plugin:1.12.0",
jirarequirements: 'net.serenity-bdd:serenity-jira-requirements-provider:1.12.0'

**Comment by wakaleo** [comment]
This has not been released yet.

**Comment by coumarine** [comment]
@wakaleo If it's not released, please advise JIRA version with which the serenity-jira-plugin:1.12.0 would work.

**Comment by wakaleo** [comment]
I don't know, I haven't been keeping track of the JIRA API changes.

**Comment by coumarine** [comment]
Ok thanks @wakaleo 
When would the change be released, please?

**Comment by coumarine** [comment]
@wakaleo Any update on this, please?

**Comment by fozersahin** [comment]
May I ask when is the possible release date for this solution? @wakaleo

**Comment by greenkode** [comment]
@wakaleo Just another reminder. I also just came across this. It would be nice to know the timeline for this.

**Comment by An-dy1** [comment]
I too am having this issue. Would love the fix to be available.

**Comment by wakaleo** [comment]
It should be.

**Comment by ricardorlg-aval** [comment]
I test It against company JIRA. should I test it again, just to see if it's still working?

**Comment by wakaleo** [comment]
Did you do a local build of the whole library?

**Comment by ricardorlg-aval** [comment]
yes I did it, and run my project using the snapshot, and it works, I will do it again and let u know.

**Comment by wakaleo** [comment]
OK, if you can check again with the latest snapshot I will do a release.

**Comment by Luciano-Cruz** [comment]
Is this going to get released any time soon?

**Pull request merged**
